language: go
go:
  - "1.12.x"
  - "1.11.x"
  - "1.10.x"
  - "1.9.x"
  - "1.8.x"
env:
  global:
    - GO111MODULE=on
script:
  - if [ $TRAVIS_GO_VERSION = "1.12.x" ]; then go test -race -p=8 -parallel=8 -coverprofile=coverage.txt ./...; fi
  - if [ $TRAVIS_GO_VERSION != "1.12.x" ]; then go test -race -p=8 -parallel=8 ./...; fi
after_success:
  - if [ $TRAVIS_GO_VERSION = "1.12.x" ]; then bash <(curl -s https://codecov.io/bash); fi

jobs:
  include:
    - stage: lint
      go: "1.12.x"
      before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.17.1
        - golangci-lint --version
      script:
        - golangci-lint run
        - echo "Check that go.mod and go.sum are tidy"
        - go mod tidy
        - if [[ `git status --porcelain go.mod` ]]; then git diff -- go.mod && echo "go.mod is outdated" && exit 1; fi
        - if [[ `git status --porcelain go.sum` ]]; then git diff -- go.sum && echo "go.sum is outdated" && exit 1; fi